---
- hosts: all
  sudo: true
  vars:
    http_port: 80
  remote_user: root
  tasks:
#  - name: update apt cache
#    apt: update_cache=yes cache_valid_time=8600

  - name: installing mysql
    apt: name={{item}} state=present update_cache=yes cache_valid_time=9600
    with_items:
      - "mysql-server"
      - "unzip"
      - "python-pip"
      - "python-mysqldb"
      - "uwsgi"
      - "uwsgi-plugin-python"

  - name: Copying init
    shell: rm -f /etc/init/app.conf;cp -f /tmp/5trips/app.conf /etc/init/app.conf

  - name: Copying application
    shell: mkdir -p /app/; rm -f /app/*.py; cp -f /tmp/5trips/app/*.py /app

  - name: Copying application settings
    shell: rm -f /app/*.yml; cp -f /tmp/5trips/app/*.yml /app

  - name: Start application
    service:
      name: app
      state: started
      enabled: yes

#  - file:
#      path: /var/lib/gtfs
#      state: absent
#      mode: 0755
#
#  - file:
#      path: /var/lib/gtfs
#      state: directory
#      mode: 0755

  - name: Getfile
    get_url: url="ftp://gtfs.mot.gov.il/israel-public-transportation.zip" dest="/tmp/israel-public-transportation.zip"
    register: get_artifact

  - name: Extracting files
    shell: rm -rf /var/lib/gtfs; mkdir -p /var/lib/gtfs;unzip -o /tmp/israel-public-transportation.zip -d /var/lib/gtfs
    when: get_artifact|changed

  - name: Installing Aplication python dependencies
    pip: name={{item}} state=present
    with_items:
      - "falcon"


  - name: Creating database
    shell: /usr/bin/mysql -uroot  -e "CREATE DATABASE IF NOT EXISTS gtfs;"
    when: get_artifact|changed

  - name: Import schema
    shell: /usr/bin/mysql -uroot gtfs < /tmp/5trips/sql/schema.txt
    ignore_errors: yes
    when: get_artifact|changed

  - name: Import data
    shell: /usr/bin/mysql -uroot gtfs --enable-local-infile  -e"LOAD DATA LOCAL INFILE '{{item.path}}' INTO TABLE {{item.table}} FIELDS TERMINATED BY ',' ;"
#
#    --local_infile=1 -e "use gtfs" -e"LOAD DATA LOCAL INFILE '{{item.path}}'
#        IGNORE INTO TABLE {{item.table}}
#        FIELDS TERMINATED BY '\t'
#        OPTIONALLY ENCLOSED BY '\"'"

    with_items:
      - { path: "/var/lib/gtfs/agency.txt", table: "agency" }
      - { path: "/var/lib/gtfs/trips.txt", table: "trips" }
      - { path: "/var/lib/gtfs/routes.txt", table: "routes" }
      - { path: "/var/lib/gtfs/calendar.txt", table: "calendar" }
      - { path: "/var/lib/gtfs/shapes.txt", table: "shapes" }
      - { path: "/var/lib/gtfs/stops.txt", table: "stops" }
      - { path: "/var/lib/gtfs/stop_times.txt", table: "stop_times" }
#      - { path: "/var/lib/gtfs/translations.txt", table: "translations" }
    ignore_errors: yes
    when: get_artifact|changed

  - name: Restart application
    service:
      name: app
      state: restarted
