---
- hosts: all
  sudo: true
  vars:
    http_port: 80
  remote_user: root
  tasks:
#  - name: update apt cache
#    apt: update_cache=yes cache_valid_time=8600

  - name: installing mysql
    apt: name={{item}} state=present update_cache=yes cache_valid_time=9600
    with_items:
      - "mysql-server"
      - "unzip"
      - "python-pip"
      - "python-mysqldb"
      - "uwsgi"

  - name: Copying init
    shell: rm -f /etc/init/app.conf;cp -f /tmp/5trips/app.conf /etc/init/app.conf

  - name: Copying application
    shell: mkdir -p /app/; rm -f /app/*.py; cp -f /tmp/5trips/app/*.py /app

#  - file:
#      path: /var/lib/gtfs
#      state: absent
#      mode: 0755
#
#  - file:
#      path: /var/lib/gtfs
#      state: directory
#      mode: 0755

  - name: Getfile
    get_url: url="ftp://gtfs.mot.gov.il/israel-public-transportation.zip" dest="/tmp/israel-public-transportation.zip"

  - name: Extracting files
    shell: unzip /tmp/israel-public-transportation.zip -d /var/lib/gtfs

  - name: Installing Aplication python dependencies
    pip: name={{item}} state=present
    with_items:
      - "falcon"
